# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ztn/Embedded/ECE385Final_S7_Slave/HDL/ChampaignBoard_S7.xdc

# Block Designs: bd/main_bd/main_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd || ORIG_REF_NAME==main_bd} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_microblaze_0_0/main_bd_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_microblaze_0_0 || ORIG_REF_NAME==main_bd_microblaze_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_dlmb_v10_0/main_bd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_dlmb_v10_0 || ORIG_REF_NAME==main_bd_dlmb_v10_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_ilmb_v10_0/main_bd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_ilmb_v10_0 || ORIG_REF_NAME==main_bd_ilmb_v10_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_dlmb_bram_if_cntlr_0/main_bd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_bd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_ilmb_bram_if_cntlr_0/main_bd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_bd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_lmb_bram_0/main_bd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_lmb_bram_0 || ORIG_REF_NAME==main_bd_lmb_bram_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_xbar_0/main_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_xbar_0 || ORIG_REF_NAME==main_bd_xbar_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_microblaze_0_axi_periph_0/main_bd_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_microblaze_0_axi_periph_0 || ORIG_REF_NAME==main_bd_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_microblaze_0_axi_intc_0/main_bd_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_microblaze_0_axi_intc_0 || ORIG_REF_NAME==main_bd_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_microblaze_0_xlconcat_0/main_bd_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_microblaze_0_xlconcat_0 || ORIG_REF_NAME==main_bd_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_mdm_1_0/main_bd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_mdm_1_0 || ORIG_REF_NAME==main_bd_mdm_1_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_clk_wiz_1_0 || ORIG_REF_NAME==main_bd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_rst_clk_wiz_1_100M_0/main_bd_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==main_bd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_uartlite_0_0/main_bd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_uartlite_0_0 || ORIG_REF_NAME==main_bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_gpio_0_0/main_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_gpio_0_0 || ORIG_REF_NAME==main_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_gpio_1_0/main_bd_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_gpio_1_0 || ORIG_REF_NAME==main_bd_axi_gpio_1_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_quad_spi_0_0/main_bd_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_quad_spi_0_0 || ORIG_REF_NAME==main_bd_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_gpio_1_1/main_bd_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_gpio_1_1 || ORIG_REF_NAME==main_bd_axi_gpio_1_1} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_axi_timer_0_0/main_bd_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_axi_timer_0_0 || ORIG_REF_NAME==main_bd_axi_timer_0_0} -quiet] -quiet

# IP: bd/main_bd/ip/main_bd_gpio_usb_keycode_0/main_bd_gpio_usb_keycode_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_bd_gpio_usb_keycode_0 || ORIG_REF_NAME==main_bd_gpio_usb_keycode_0} -quiet] -quiet

# XDC: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.gen/sources_1/bd/main_bd/main_bd_ooc.xdc
