# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.srcs/sources_1/bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0.xci
# IP: The module: 'main_bd_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.gen/sources_1/bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_bd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.gen/sources_1/bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_bd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.gen/sources_1/bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_bd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.srcs/sources_1/bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0.xci
# IP: The module: 'main_bd_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.gen/sources_1/bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_bd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.gen/sources_1/bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_bd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ztn/Embedded/ECE385Final_S7_Slave/ECE385Final_S7_Slave.gen/sources_1/bd/main_bd/ip/main_bd_clk_wiz_1_0/main_bd_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_bd_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
